---
- hosts: 10.0.3.175
  tasks:
    # TODO: install packages (build-essential libcmocka-dev libpam-wrapper libpam0g-dev)
    - name: Backup PAM configurations
      copy:
        src: /etc/pam.d/{{ item }}
        dest: /etc/pam.d/{{ item }}.bak
        remote_src: yes
        force: no
      become: yes
      with_items:
        - login
        - common-auth
    - name: Create /tmp/passdb
      blockinfile:
        dest: /tmp/passdb
        create: yes
        block: |
          root:rootsecret:login
      become: yes
    - name: Create temp dir
      tempfile:
        state: directory
        suffix: temp
      register: tempdir_1
    - name: Copy Makefile & source
      copy:
        src: "{{ playbook_dir }}/../{{ item }}"
        dest: "{{ tempdir_1.path }}/"
        mode: 0600
      with_items:
        - Makefile
        - tests/test.c
    - name: Build PAM test
      make:
        chdir: "{{ tempdir_1.path }}"
        target: test
    - name: Make sure pam_securetty is enabled for login
      replace:
        path: /etc/pam.d/login
        regexp: '^#?\s*(auth\s+\[success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die\]\s+pam_securetty\.so)$'
        replace: '\1'
        validate: '/bin/grep "^auth\s\+\[success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die\]\s\+pam_securetty\.so$" %s'
      become: yes
    # authentication should fail as pam_matrix is not yet in use
    - name: Run first test
      command: "{{ tempdir_1.path }}/test"
    - name: Copy pam_matrix pam-config
      copy:
        src: "{{ playbook_dir }}/../newconfs/pam-configs/matrix.new"
        dest: /usr/share/pam-configs/matrix
      become: yes
    - name: Update PAM
      become: yes
      command: /usr/sbin/pam-auth-update --package
    # should fail because of pam_securetty
    - name: Run test #2
      command: "{{ tempdir_1.path }}/test"
    # TODO: disable securetty
    # TODO: run phase 2
    #- name: Remove temp dir
    #  file:
    #    path: "{{ tempdir_1.path }}"
    #    state: absent
    #  when: tempdir_1.path is defined
