---
- name: Set file permissions/ownership for sudoers
  ansible.builtin.file:
    path: /etc/{{ item }}
    mode: g-w,o-rwx
    owner: root
    group: root
  become: true
  tags:
    - permissions
    - sudo
  with_items:
    - sudoers.d
    - sudoers
# ANSSI BP-028 R38 - Creating a group dedicated to the use of sudo
- name: Set file permissions/ownership for sudo
  ansible.builtin.file:
    path: /usr/bin/sudo
    mode: '4750'
    owner: root
    group: '{{ sudo_group }}'
  become: true
  tags:
    - permissions
    - sudo
    - suid
