name: ca-certs
on: [push, pull_request]

jobs:
  ca-certs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show ca-certificates version
        run: apt-cache show ca-certificates
      - name: Run test_ca-certs.sh
        run: bash tests/test_ca-certs.sh
  crls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Show ca-certificates version
        run: apt-cache show ca-certificates
      - name: Fetch CRLs
        run: sudo make crls
