name: lint
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: ./harden.yml
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint ./*.yml tasks/*.yml
