name: molecule
on: [push, pull_request]

env:
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  molecule-slackware:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install --user molecule[docker] molecule-plugins[docker]
      - name: Run Molecule
        run: molecule test
